import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import axios from 'axios';

export const api = axios.create({
  baseURL: 'http://localhost:3000',
});

const moodEmojis = [
  { id: 1, pic: '😊' },
  { id: 2, pic: '😄 ' },
  { id: 3, pic: '😊' },
  { id: 4, pic: '🥶' },
  { id: 5, pic: '😮' },
];

async function toggleClick(id: number): Promise<void> {
  console.log(id);
  const res = await api.post('/moods', {
    mood: id,
  });
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Message in a Bottle!</a>
        </h1>

        <div className={styles.grid}>
          <div>
            <h1>How are you today? </h1>
          </div>

          <div className={styles.grid}>
            {moodEmojis.map((emoji) => {
              return (
                <a
                  key={emoji.id}
                  href="getorpost"
                  className={styles.card}
                  onClick={async () => await toggleClick(emoji.id)}
                >
                  <p>{emoji.pic}</p>
                </a>
              );
            })}
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.arol.dev/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by QUACK TEAM
          <br />
          <img
            src="https://ih1.redbubble.net/image.12004786.2619/raf,750x1000,075,t,EDE272:cfc3479bac.u4.jpg"
            width={50}
            height={50}
          />
        </a>
      </footer>
    </div>
  );
};

export default Home;
